updated cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,4 +1,4 @@
-name: Java CI with Maven and Snyk
+name: Java CI with Maven
 
 on:
   push:
@@ -36,27 +36,67 @@ jobs:
       if: github.ref == 'refs/heads/development'
       run: mvn test
 
-    - name: Snyk Maven Dependency Scan
+    - name: Run Snyk Maven Dependency Scan
       uses: snyk/actions/maven-3-jdk-17@master
       continue-on-error: true
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       with:
-        args: --sarif-file-output=snyk.sarif
+        args: --all-projects
 
-    - name: Upload Snyk results to GitHub Code Scanning
-      uses: github/codeql-action/upload-sarif@v3
+    - name: Update Maven version
+      if: success()
+      id: update_version
+      run: |
+        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
+        if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
+          NEW_MINOR=$((MINOR+1))
+          NEW_VERSION="$MAJOR.$NEW_MINOR.0"
+        elif [[ $GITHUB_REF == 'refs/heads/development' ]]; then
+          NEW_PATCH=$((PATCH+1))
+          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
+        else
+          echo "Not a monitored branch. Skipping version increment."
+          exit 0
+        fi
+        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
+        echo "NEW_VERSION: $NEW_VERSION" # Debugging line to check the value of NEW_VERSION
+        # Update the version in pom.xml
+        mvn versions:set -DnewVersion=$NEW_VERSION
+    
+    - name: Upload artifact
+      uses: actions/upload-artifact@v4
       with:
-        sarif_file: snyk.sarif
+        name: my-app-${{ env.new_version }}
+        path: target/*.jar
+
+    - name: Login to Docker Hub
+      uses: docker/login-action@v3
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
 
     - name: Build and Push Docker Image
       if: github.ref == 'refs/heads/master'
+      id: docker_build
       uses: docker/build-push-action@v5
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.new_version }}
+
+    - name: Commit and push new version
+      if: success()
+      run: |
+        git config --global user.name 'github-actions[bot]'
+        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+        git add pom.xml
+        git commit -m "Update version to ${{ env.new_version }}"
+        git push
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Deploy Docker Image
       if: github.ref == 'refs/heads/master'
@@ -67,6 +107,21 @@ jobs:
         ssh -o StrictHostKeyChecking=no -i "~/.ssh/id_rsa" ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
           docker pull ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.new_version }}
+    
+          # Clean up unused containers and images
+          docker container prune -f
+          docker image prune -f
+    
+          # Check if the container is running and stop/remove if necessary
+          if [ $(docker ps -aq -f name=my-app) ]; then
+            echo "Stopping and removing existing container"
+            docker stop my-app || true
+            docker rm my-app || true
+          else
+            echo "No existing container to stop and remove"
+          fi
+          
+          # Run the new container
           docker run -d --name my-app -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.new_version }}
         EOF
       env:
